# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4de607583fcc1c1b5d54c9f489d7201f01b8db68fc88358f5756cfb3e84fcee35fd1fe5e6f2ef010191061fdc29082dd566964b57b76e9dfb5e4684e1d8de80d

test:
  secret_key_base: 90a3daedc2a4db9bcf107d0c15d8b303891e25ed5b468461da635c9cde8643ad16a53de9d79d35f2964a54d16b9660c63ee97e4043c5419e409f2370eb5fff32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
